apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-mc-webapp
spec: 
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  - name: frontend
    image: procosys.azurecr.io/procosys/mc-webapp:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: 9f056ccb-c53e-4e15-859f-95027bff2ae5
      imageTagName: latest  
      variables:
        pcs_authSettingsEndpoint: 'https://pcs-config-non-prod-func.azurewebsites.net/api/MCWebApp/Auth'
      monitoring: true
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'      
    # Test environment
    - environment: test
      identity:
        azure:
          clientId: 912690c2-dbea-4174-a9fd-3c85f113435c
      variables:
        pcs_authSettingsEndpoint: 'https://pcs-config-non-prod-func.azurewebsites.net/api/MCWebApp/Auth'
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'      
    # Production environment
    - environment: prod
      identity:
        azure:
          clientId: 437b9c0c-fe8f-4388-ab9e-ca2d5b53530e
      variables:
        pcs_authSettingsEndpoint: 'https://pcs-config-prod-func.azurewebsites.net/api/MCWebApp/Auth'
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'      
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896

