apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-mc-webapp
spec:
  environments:
  - name: dev
    build:
      from: develop
  - name: test
    build:
      from: test
  - name: prod
    build:
      from: main
  components:
  - name: frontend
    publicPort: http
    ports:
    - name: http
      port: 5000
    environmentConfig:
    - environment: dev
      dockerfileName: Dockerfile.dev
    - environment: test
      dockerfileName: Dockerfile.test
    - environment: prod
      dockerfileName: Dockerfile.prod